/**
 * This class is generated by jOOQ
 */
package sooth.entities.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Attachments extends org.jooq.impl.TableImpl<sooth.entities.tables.records.AttachmentsRecord> {

	private static final long serialVersionUID = -1285631190;

	/**
	 * The reference instance of <code>asmregen.attachments</code>
	 */
	public static final sooth.entities.tables.Attachments ATTACHMENTS = new sooth.entities.tables.Attachments();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<sooth.entities.tables.records.AttachmentsRecord> getRecordType() {
		return sooth.entities.tables.records.AttachmentsRecord.class;
	}

	/**
	 * The column <code>asmregen.attachments.id</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.AttachmentsRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>asmregen.attachments.name</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.AttachmentsRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>asmregen.attachments.type</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.AttachmentsRecord, java.lang.String> TYPE = createField("type", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>asmregen.attachments.file</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.AttachmentsRecord, java.lang.String> FILE = createField("file", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>asmregen.attachments.lectureId</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.AttachmentsRecord, java.lang.Integer> LECTUREID = createField("lectureId", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>asmregen.attachments</code> table reference
	 */
	public Attachments() {
		this("attachments", null);
	}

	/**
	 * Create an aliased <code>asmregen.attachments</code> table reference
	 */
	public Attachments(java.lang.String alias) {
		this(alias, sooth.entities.tables.Attachments.ATTACHMENTS);
	}

	private Attachments(java.lang.String alias, org.jooq.Table<sooth.entities.tables.records.AttachmentsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Attachments(java.lang.String alias, org.jooq.Table<sooth.entities.tables.records.AttachmentsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, sooth.entities.Asmregen.ASMREGEN, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<sooth.entities.tables.records.AttachmentsRecord, java.lang.Integer> getIdentity() {
		return sooth.entities.Keys.IDENTITY_ATTACHMENTS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<sooth.entities.tables.records.AttachmentsRecord> getPrimaryKey() {
		return sooth.entities.Keys.KEY_ATTACHMENTS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<sooth.entities.tables.records.AttachmentsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<sooth.entities.tables.records.AttachmentsRecord>>asList(sooth.entities.Keys.KEY_ATTACHMENTS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<sooth.entities.tables.records.AttachmentsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<sooth.entities.tables.records.AttachmentsRecord, ?>>asList(sooth.entities.Keys.FK_47C4FAD63BC48E00);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public sooth.entities.tables.Attachments as(java.lang.String alias) {
		return new sooth.entities.tables.Attachments(alias, this);
	}

	/**
	 * Rename this table
	 */
	public sooth.entities.tables.Attachments rename(java.lang.String name) {
		return new sooth.entities.tables.Attachments(name, null);
	}
}
