/**
 * This class is generated by jOOQ
 */
package sooth.entities.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Groups extends org.jooq.impl.TableImpl<sooth.entities.tables.records.GroupsRecord> {

	private static final long serialVersionUID = 576960186;

	/**
	 * The reference instance of <code>asmregen.groups</code>
	 */
	public static final sooth.entities.tables.Groups GROUPS = new sooth.entities.tables.Groups();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<sooth.entities.tables.records.GroupsRecord> getRecordType() {
		return sooth.entities.tables.records.GroupsRecord.class;
	}

	/**
	 * The column <code>asmregen.groups.id</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.GroupsRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>asmregen.groups.name</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.GroupsRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>asmregen.groups.description</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.GroupsRecord, java.lang.String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>asmregen.groups.ownerId</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.GroupsRecord, java.lang.Integer> OWNERID = createField("ownerId", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>asmregen.groups.type</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.GroupsRecord, java.lang.String> TYPE = createField("type", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>asmregen.groups.lectureId</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.GroupsRecord, java.lang.Integer> LECTUREID = createField("lectureId", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>asmregen.groups.deleted</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.GroupsRecord, java.lang.Byte> DELETED = createField("deleted", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

	/**
	 * Create a <code>asmregen.groups</code> table reference
	 */
	public Groups() {
		this("groups", null);
	}

	/**
	 * Create an aliased <code>asmregen.groups</code> table reference
	 */
	public Groups(java.lang.String alias) {
		this(alias, sooth.entities.tables.Groups.GROUPS);
	}

	private Groups(java.lang.String alias, org.jooq.Table<sooth.entities.tables.records.GroupsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Groups(java.lang.String alias, org.jooq.Table<sooth.entities.tables.records.GroupsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, sooth.entities.Asmregen.ASMREGEN, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<sooth.entities.tables.records.GroupsRecord, java.lang.Integer> getIdentity() {
		return sooth.entities.Keys.IDENTITY_GROUPS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<sooth.entities.tables.records.GroupsRecord> getPrimaryKey() {
		return sooth.entities.Keys.KEY_GROUPS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<sooth.entities.tables.records.GroupsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<sooth.entities.tables.records.GroupsRecord>>asList(sooth.entities.Keys.KEY_GROUPS_PRIMARY, sooth.entities.Keys.KEY_GROUPS_NAME);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<sooth.entities.tables.records.GroupsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<sooth.entities.tables.records.GroupsRecord, ?>>asList(sooth.entities.Keys.FK_F06D3970E05EFD25, sooth.entities.Keys.FK_F06D39703BC48E00);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public sooth.entities.tables.Groups as(java.lang.String alias) {
		return new sooth.entities.tables.Groups(alias, this);
	}

	/**
	 * Rename this table
	 */
	public sooth.entities.tables.Groups rename(java.lang.String name) {
		return new sooth.entities.tables.Groups(name, null);
	}
}
