/**
 * This class is generated by jOOQ
 */
package sooth.entities.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Lectures extends org.jooq.impl.TableImpl<sooth.entities.tables.records.LecturesRecord> {

	private static final long serialVersionUID = 1545376658;

	/**
	 * The reference instance of <code>asmregen.lectures</code>
	 */
	public static final sooth.entities.tables.Lectures LECTURES = new sooth.entities.tables.Lectures();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<sooth.entities.tables.records.LecturesRecord> getRecordType() {
		return sooth.entities.tables.records.LecturesRecord.class;
	}

	/**
	 * The column <code>asmregen.lectures.id</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.LecturesRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>asmregen.lectures.name</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.LecturesRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>asmregen.lectures.description</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.LecturesRecord, java.lang.String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>asmregen.lectures.ownerId</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.LecturesRecord, java.lang.Integer> OWNERID = createField("ownerId", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>asmregen.lectures.deleted</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.LecturesRecord, java.lang.Byte> DELETED = createField("deleted", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

	/**
	 * Create a <code>asmregen.lectures</code> table reference
	 */
	public Lectures() {
		this("lectures", null);
	}

	/**
	 * Create an aliased <code>asmregen.lectures</code> table reference
	 */
	public Lectures(java.lang.String alias) {
		this(alias, sooth.entities.tables.Lectures.LECTURES);
	}

	private Lectures(java.lang.String alias, org.jooq.Table<sooth.entities.tables.records.LecturesRecord> aliased) {
		this(alias, aliased, null);
	}

	private Lectures(java.lang.String alias, org.jooq.Table<sooth.entities.tables.records.LecturesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, sooth.entities.Asmregen.ASMREGEN, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<sooth.entities.tables.records.LecturesRecord, java.lang.Integer> getIdentity() {
		return sooth.entities.Keys.IDENTITY_LECTURES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<sooth.entities.tables.records.LecturesRecord> getPrimaryKey() {
		return sooth.entities.Keys.KEY_LECTURES_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<sooth.entities.tables.records.LecturesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<sooth.entities.tables.records.LecturesRecord>>asList(sooth.entities.Keys.KEY_LECTURES_PRIMARY, sooth.entities.Keys.KEY_LECTURES_NAME);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<sooth.entities.tables.records.LecturesRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<sooth.entities.tables.records.LecturesRecord, ?>>asList(sooth.entities.Keys.FK_63C861D0E05EFD25);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public sooth.entities.tables.Lectures as(java.lang.String alias) {
		return new sooth.entities.tables.Lectures(alias, this);
	}

	/**
	 * Rename this table
	 */
	public sooth.entities.tables.Lectures rename(java.lang.String name) {
		return new sooth.entities.tables.Lectures(name, null);
	}
}
