/**
 * This class is generated by jOOQ
 */
package sooth.entities.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Plugins extends org.jooq.impl.TableImpl<sooth.entities.tables.records.PluginsRecord> {

	private static final long serialVersionUID = 1413862351;

	/**
	 * The reference instance of <code>asmregen.plugins</code>
	 */
	public static final sooth.entities.tables.Plugins PLUGINS = new sooth.entities.tables.Plugins();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<sooth.entities.tables.records.PluginsRecord> getRecordType() {
		return sooth.entities.tables.records.PluginsRecord.class;
	}

	/**
	 * The column <code>asmregen.plugins.id</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.PluginsRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>asmregen.plugins.name</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.PluginsRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>asmregen.plugins.type</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.PluginsRecord, java.lang.String> TYPE = createField("type", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>asmregen.plugins.description</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.PluginsRecord, java.lang.String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>asmregen.plugins.mainFile</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.PluginsRecord, java.lang.String> MAINFILE = createField("mainFile", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>asmregen.plugins.config</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.PluginsRecord, java.lang.String> CONFIG = createField("config", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>asmregen.plugins.identifier</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.PluginsRecord, java.lang.String> IDENTIFIER = createField("identifier", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * Create a <code>asmregen.plugins</code> table reference
	 */
	public Plugins() {
		this("plugins", null);
	}

	/**
	 * Create an aliased <code>asmregen.plugins</code> table reference
	 */
	public Plugins(java.lang.String alias) {
		this(alias, sooth.entities.tables.Plugins.PLUGINS);
	}

	private Plugins(java.lang.String alias, org.jooq.Table<sooth.entities.tables.records.PluginsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Plugins(java.lang.String alias, org.jooq.Table<sooth.entities.tables.records.PluginsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, sooth.entities.Asmregen.ASMREGEN, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<sooth.entities.tables.records.PluginsRecord, java.lang.Integer> getIdentity() {
		return sooth.entities.Keys.IDENTITY_PLUGINS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<sooth.entities.tables.records.PluginsRecord> getPrimaryKey() {
		return sooth.entities.Keys.KEY_PLUGINS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<sooth.entities.tables.records.PluginsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<sooth.entities.tables.records.PluginsRecord>>asList(sooth.entities.Keys.KEY_PLUGINS_PRIMARY, sooth.entities.Keys.KEY_PLUGINS_NAME, sooth.entities.Keys.KEY_PLUGINS_FOLDER);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public sooth.entities.tables.Plugins as(java.lang.String alias) {
		return new sooth.entities.tables.Plugins(alias, this);
	}

	/**
	 * Rename this table
	 */
	public sooth.entities.tables.Plugins rename(java.lang.String name) {
		return new sooth.entities.tables.Plugins(name, null);
	}
}
