/**
 * This class is generated by jOOQ
 */
package sooth.entities.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Privileges extends org.jooq.impl.TableImpl<sooth.entities.tables.records.PrivilegesRecord> {

	private static final long serialVersionUID = -850291582;

	/**
	 * The reference instance of <code>asmregen.privileges</code>
	 */
	public static final sooth.entities.tables.Privileges PRIVILEGES = new sooth.entities.tables.Privileges();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<sooth.entities.tables.records.PrivilegesRecord> getRecordType() {
		return sooth.entities.tables.records.PrivilegesRecord.class;
	}

	/**
	 * The column <code>asmregen.privileges.id</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.PrivilegesRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>asmregen.privileges.name</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.PrivilegesRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>asmregen.privileges.privileges</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.PrivilegesRecord, java.lang.Integer> PRIVILEGES_ = createField("privileges", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>asmregen.privileges</code> table reference
	 */
	public Privileges() {
		this("privileges", null);
	}

	/**
	 * Create an aliased <code>asmregen.privileges</code> table reference
	 */
	public Privileges(java.lang.String alias) {
		this(alias, sooth.entities.tables.Privileges.PRIVILEGES);
	}

	private Privileges(java.lang.String alias, org.jooq.Table<sooth.entities.tables.records.PrivilegesRecord> aliased) {
		this(alias, aliased, null);
	}

	private Privileges(java.lang.String alias, org.jooq.Table<sooth.entities.tables.records.PrivilegesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, sooth.entities.Asmregen.ASMREGEN, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<sooth.entities.tables.records.PrivilegesRecord, java.lang.Integer> getIdentity() {
		return sooth.entities.Keys.IDENTITY_PRIVILEGES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<sooth.entities.tables.records.PrivilegesRecord> getPrimaryKey() {
		return sooth.entities.Keys.KEY_PRIVILEGES_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<sooth.entities.tables.records.PrivilegesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<sooth.entities.tables.records.PrivilegesRecord>>asList(sooth.entities.Keys.KEY_PRIVILEGES_PRIMARY, sooth.entities.Keys.KEY_PRIVILEGES_NAME);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public sooth.entities.tables.Privileges as(java.lang.String alias) {
		return new sooth.entities.tables.Privileges(alias, this);
	}

	/**
	 * Rename this table
	 */
	public sooth.entities.tables.Privileges rename(java.lang.String name) {
		return new sooth.entities.tables.Privileges(name, null);
	}
}
