/**
 * This class is generated by jOOQ
 */
package sooth.entities.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Submissions extends org.jooq.impl.TableImpl<sooth.entities.tables.records.SubmissionsRecord> {

	private static final long serialVersionUID = 1484923784;

	/**
	 * The reference instance of <code>asmregen.submissions</code>
	 */
	public static final sooth.entities.tables.Submissions SUBMISSIONS = new sooth.entities.tables.Submissions();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<sooth.entities.tables.records.SubmissionsRecord> getRecordType() {
		return sooth.entities.tables.records.SubmissionsRecord.class;
	}

	/**
	 * The column <code>asmregen.submissions.id</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubmissionsRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>asmregen.submissions.assignmentId</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubmissionsRecord, java.lang.Integer> ASSIGNMENTID = createField("assignmentId", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>asmregen.submissions.userId</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubmissionsRecord, java.lang.Integer> USERID = createField("userId", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>asmregen.submissions.submissionFile</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubmissionsRecord, java.lang.String> SUBMISSIONFILE = createField("submissionFile", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>asmregen.submissions.date</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubmissionsRecord, java.sql.Timestamp> DATE = createField("date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>asmregen.submissions.status</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubmissionsRecord, java.lang.String> STATUS = createField("status", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>asmregen.submissions.success</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubmissionsRecord, java.lang.Integer> SUCCESS = createField("success", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>asmregen.submissions.info</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubmissionsRecord, java.lang.String> INFO = createField("info", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>asmregen.submissions.outputFile</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubmissionsRecord, java.lang.String> OUTPUTFILE = createField("outputFile", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>asmregen.submissions.rating</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubmissionsRecord, java.lang.Integer> RATING = createField("rating", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>asmregen.submissions.explanation</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubmissionsRecord, java.lang.String> EXPLANATION = createField("explanation", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>asmregen.submissions.similarityStatus</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubmissionsRecord, java.lang.String> SIMILARITYSTATUS = createField("similarityStatus", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * Create a <code>asmregen.submissions</code> table reference
	 */
	public Submissions() {
		this("submissions", null);
	}

	/**
	 * Create an aliased <code>asmregen.submissions</code> table reference
	 */
	public Submissions(java.lang.String alias) {
		this(alias, sooth.entities.tables.Submissions.SUBMISSIONS);
	}

	private Submissions(java.lang.String alias, org.jooq.Table<sooth.entities.tables.records.SubmissionsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Submissions(java.lang.String alias, org.jooq.Table<sooth.entities.tables.records.SubmissionsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, sooth.entities.Asmregen.ASMREGEN, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<sooth.entities.tables.records.SubmissionsRecord, java.lang.Integer> getIdentity() {
		return sooth.entities.Keys.IDENTITY_SUBMISSIONS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<sooth.entities.tables.records.SubmissionsRecord> getPrimaryKey() {
		return sooth.entities.Keys.KEY_SUBMISSIONS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<sooth.entities.tables.records.SubmissionsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<sooth.entities.tables.records.SubmissionsRecord>>asList(sooth.entities.Keys.KEY_SUBMISSIONS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<sooth.entities.tables.records.SubmissionsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<sooth.entities.tables.records.SubmissionsRecord, ?>>asList(sooth.entities.Keys.FK_3F6169F74526B08C, sooth.entities.Keys.FK_3F6169F764B64DCC);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public sooth.entities.tables.Submissions as(java.lang.String alias) {
		return new sooth.entities.tables.Submissions(alias, this);
	}

	/**
	 * Rename this table
	 */
	public sooth.entities.tables.Submissions rename(java.lang.String name) {
		return new sooth.entities.tables.Submissions(name, null);
	}
}
