/**
 * This class is generated by jOOQ
 */
package sooth.entities.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Subscriptions extends org.jooq.impl.TableImpl<sooth.entities.tables.records.SubscriptionsRecord> {

	private static final long serialVersionUID = -886578594;

	/**
	 * The reference instance of <code>asmregen.subscriptions</code>
	 */
	public static final sooth.entities.tables.Subscriptions SUBSCRIPTIONS = new sooth.entities.tables.Subscriptions();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<sooth.entities.tables.records.SubscriptionsRecord> getRecordType() {
		return sooth.entities.tables.records.SubscriptionsRecord.class;
	}

	/**
	 * The column <code>asmregen.subscriptions.id</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubscriptionsRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>asmregen.subscriptions.userId</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubscriptionsRecord, java.lang.Integer> USERID = createField("userId", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>asmregen.subscriptions.groupId</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubscriptionsRecord, java.lang.Integer> GROUPID = createField("groupId", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>asmregen.subscriptions.status</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubscriptionsRecord, java.lang.String> STATUS = createField("status", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * Create a <code>asmregen.subscriptions</code> table reference
	 */
	public Subscriptions() {
		this("subscriptions", null);
	}

	/**
	 * Create an aliased <code>asmregen.subscriptions</code> table reference
	 */
	public Subscriptions(java.lang.String alias) {
		this(alias, sooth.entities.tables.Subscriptions.SUBSCRIPTIONS);
	}

	private Subscriptions(java.lang.String alias, org.jooq.Table<sooth.entities.tables.records.SubscriptionsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Subscriptions(java.lang.String alias, org.jooq.Table<sooth.entities.tables.records.SubscriptionsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, sooth.entities.Asmregen.ASMREGEN, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<sooth.entities.tables.records.SubscriptionsRecord, java.lang.Integer> getIdentity() {
		return sooth.entities.Keys.IDENTITY_SUBSCRIPTIONS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<sooth.entities.tables.records.SubscriptionsRecord> getPrimaryKey() {
		return sooth.entities.Keys.KEY_SUBSCRIPTIONS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<sooth.entities.tables.records.SubscriptionsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<sooth.entities.tables.records.SubscriptionsRecord>>asList(sooth.entities.Keys.KEY_SUBSCRIPTIONS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<sooth.entities.tables.records.SubscriptionsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<sooth.entities.tables.records.SubscriptionsRecord, ?>>asList(sooth.entities.Keys.FK_4778A0164B64DCC, sooth.entities.Keys.FK_4778A01ED8188B0);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public sooth.entities.tables.Subscriptions as(java.lang.String alias) {
		return new sooth.entities.tables.Subscriptions(alias, this);
	}

	/**
	 * Rename this table
	 */
	public sooth.entities.tables.Subscriptions rename(java.lang.String name) {
		return new sooth.entities.tables.Subscriptions(name, null);
	}
}
