/**
 * Contains classes that represent database entities. However, these are not automatically generated by jOOQ.
 * 
 * We don't use actual jOOQ-generated entity classes in main code because:
 * - we might want to add custom functionality to these classes and jOOQ classes might be regenerated at any time
 * - we want our classes to be more lightweight and to be plain java objects
 */
package sooth.objects;