/**
 * This class is generated by jOOQ
 */
package sooth.entities.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AssignmentsRecord extends org.jooq.impl.UpdatableRecordImpl<sooth.entities.tables.records.AssignmentsRecord> implements org.jooq.Record6<java.lang.Integer, java.sql.Timestamp, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Byte> {

	private static final long serialVersionUID = -818120928;

	/**
	 * Setter for <code>asmregen.assignments.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>asmregen.assignments.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>asmregen.assignments.deadline</code>.
	 */
	public void setDeadline(java.sql.Timestamp value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>asmregen.assignments.deadline</code>.
	 */
	public java.sql.Timestamp getDeadline() {
		return (java.sql.Timestamp) getValue(1);
	}

	/**
	 * Setter for <code>asmregen.assignments.reward</code>.
	 */
	public void setReward(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>asmregen.assignments.reward</code>.
	 */
	public java.lang.Integer getReward() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>asmregen.assignments.groupId</code>.
	 */
	public void setGroupid(java.lang.Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>asmregen.assignments.groupId</code>.
	 */
	public java.lang.Integer getGroupid() {
		return (java.lang.Integer) getValue(3);
	}

	/**
	 * Setter for <code>asmregen.assignments.problemId</code>.
	 */
	public void setProblemid(java.lang.Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>asmregen.assignments.problemId</code>.
	 */
	public java.lang.Integer getProblemid() {
		return (java.lang.Integer) getValue(4);
	}

	/**
	 * Setter for <code>asmregen.assignments.deleted</code>.
	 */
	public void setDeleted(java.lang.Byte value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>asmregen.assignments.deleted</code>.
	 */
	public java.lang.Byte getDeleted() {
		return (java.lang.Byte) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Integer, java.sql.Timestamp, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Byte> fieldsRow() {
		return (org.jooq.Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Integer, java.sql.Timestamp, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Byte> valuesRow() {
		return (org.jooq.Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return sooth.entities.tables.Assignments.ASSIGNMENTS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field2() {
		return sooth.entities.tables.Assignments.ASSIGNMENTS.DEADLINE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return sooth.entities.tables.Assignments.ASSIGNMENTS.REWARD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field4() {
		return sooth.entities.tables.Assignments.ASSIGNMENTS.GROUPID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field5() {
		return sooth.entities.tables.Assignments.ASSIGNMENTS.PROBLEMID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field6() {
		return sooth.entities.tables.Assignments.ASSIGNMENTS.DELETED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value2() {
		return getDeadline();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getReward();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value4() {
		return getGroupid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value5() {
		return getProblemid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value6() {
		return getDeleted();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AssignmentsRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AssignmentsRecord value2(java.sql.Timestamp value) {
		setDeadline(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AssignmentsRecord value3(java.lang.Integer value) {
		setReward(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AssignmentsRecord value4(java.lang.Integer value) {
		setGroupid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AssignmentsRecord value5(java.lang.Integer value) {
		setProblemid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AssignmentsRecord value6(java.lang.Byte value) {
		setDeleted(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AssignmentsRecord values(java.lang.Integer value1, java.sql.Timestamp value2, java.lang.Integer value3, java.lang.Integer value4, java.lang.Integer value5, java.lang.Byte value6) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AssignmentsRecord
	 */
	public AssignmentsRecord() {
		super(sooth.entities.tables.Assignments.ASSIGNMENTS);
	}

	/**
	 * Create a detached, initialised AssignmentsRecord
	 */
	public AssignmentsRecord(java.lang.Integer id, java.sql.Timestamp deadline, java.lang.Integer reward, java.lang.Integer groupid, java.lang.Integer problemid, java.lang.Byte deleted) {
		super(sooth.entities.tables.Assignments.ASSIGNMENTS);

		setValue(0, id);
		setValue(1, deadline);
		setValue(2, reward);
		setValue(3, groupid);
		setValue(4, problemid);
		setValue(5, deleted);
	}
}
