/**
 * This class is generated by jOOQ
 */
package sooth.entities.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PluginsRecord extends org.jooq.impl.UpdatableRecordImpl<sooth.entities.tables.records.PluginsRecord> implements org.jooq.Record7<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = 1562166702;

	/**
	 * Setter for <code>asmregen.plugins.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>asmregen.plugins.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>asmregen.plugins.name</code>.
	 */
	public void setName(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>asmregen.plugins.name</code>.
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>asmregen.plugins.type</code>.
	 */
	public void setType(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>asmregen.plugins.type</code>.
	 */
	public java.lang.String getType() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>asmregen.plugins.description</code>.
	 */
	public void setDescription(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>asmregen.plugins.description</code>.
	 */
	public java.lang.String getDescription() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>asmregen.plugins.mainFile</code>.
	 */
	public void setMainfile(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>asmregen.plugins.mainFile</code>.
	 */
	public java.lang.String getMainfile() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>asmregen.plugins.config</code>.
	 */
	public void setConfig(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>asmregen.plugins.config</code>.
	 */
	public java.lang.String getConfig() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>asmregen.plugins.identifier</code>.
	 */
	public void setIdentifier(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>asmregen.plugins.identifier</code>.
	 */
	public java.lang.String getIdentifier() {
		return (java.lang.String) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return sooth.entities.tables.Plugins.PLUGINS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return sooth.entities.tables.Plugins.PLUGINS.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return sooth.entities.tables.Plugins.PLUGINS.TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return sooth.entities.tables.Plugins.PLUGINS.DESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return sooth.entities.tables.Plugins.PLUGINS.MAINFILE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return sooth.entities.tables.Plugins.PLUGINS.CONFIG;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return sooth.entities.tables.Plugins.PLUGINS.IDENTIFIER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getDescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getMainfile();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getConfig();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getIdentifier();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PluginsRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PluginsRecord value2(java.lang.String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PluginsRecord value3(java.lang.String value) {
		setType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PluginsRecord value4(java.lang.String value) {
		setDescription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PluginsRecord value5(java.lang.String value) {
		setMainfile(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PluginsRecord value6(java.lang.String value) {
		setConfig(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PluginsRecord value7(java.lang.String value) {
		setIdentifier(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PluginsRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3, java.lang.String value4, java.lang.String value5, java.lang.String value6, java.lang.String value7) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PluginsRecord
	 */
	public PluginsRecord() {
		super(sooth.entities.tables.Plugins.PLUGINS);
	}

	/**
	 * Create a detached, initialised PluginsRecord
	 */
	public PluginsRecord(java.lang.Integer id, java.lang.String name, java.lang.String type, java.lang.String description, java.lang.String mainfile, java.lang.String config, java.lang.String identifier) {
		super(sooth.entities.tables.Plugins.PLUGINS);

		setValue(0, id);
		setValue(1, name);
		setValue(2, type);
		setValue(3, description);
		setValue(4, mainfile);
		setValue(5, config);
		setValue(6, identifier);
	}
}
