/**
 * This class is generated by jOOQ
 */
package sooth.entities.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TestsRecord extends org.jooq.impl.UpdatableRecordImpl<sooth.entities.tables.records.TestsRecord> implements org.jooq.Record9<java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = 1764482694;

	/**
	 * Setter for <code>asmregen.tests.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>asmregen.tests.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>asmregen.tests.description</code>.
	 */
	public void setDescription(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>asmregen.tests.description</code>.
	 */
	public java.lang.String getDescription() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>asmregen.tests.pluginId</code>.
	 */
	public void setPluginid(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>asmregen.tests.pluginId</code>.
	 */
	public java.lang.Integer getPluginid() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>asmregen.tests.config</code>.
	 */
	public void setConfig(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>asmregen.tests.config</code>.
	 */
	public java.lang.String getConfig() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>asmregen.tests.input</code>.
	 */
	public void setInput(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>asmregen.tests.input</code>.
	 */
	public java.lang.String getInput() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>asmregen.tests.status</code>.
	 */
	public void setStatus(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>asmregen.tests.status</code>.
	 */
	public java.lang.String getStatus() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>asmregen.tests.success</code>.
	 */
	public void setSuccess(java.lang.Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>asmregen.tests.success</code>.
	 */
	public java.lang.Integer getSuccess() {
		return (java.lang.Integer) getValue(6);
	}

	/**
	 * Setter for <code>asmregen.tests.info</code>.
	 */
	public void setInfo(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>asmregen.tests.info</code>.
	 */
	public java.lang.String getInfo() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>asmregen.tests.output</code>.
	 */
	public void setOutput(java.lang.String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>asmregen.tests.output</code>.
	 */
	public java.lang.String getOutput() {
		return (java.lang.String) getValue(8);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record9 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row9<java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row9) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row9<java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row9) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return sooth.entities.tables.Tests.TESTS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return sooth.entities.tables.Tests.TESTS.DESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return sooth.entities.tables.Tests.TESTS.PLUGINID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return sooth.entities.tables.Tests.TESTS.CONFIG;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return sooth.entities.tables.Tests.TESTS.INPUT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return sooth.entities.tables.Tests.TESTS.STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field7() {
		return sooth.entities.tables.Tests.TESTS.SUCCESS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return sooth.entities.tables.Tests.TESTS.INFO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field9() {
		return sooth.entities.tables.Tests.TESTS.OUTPUT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getDescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getPluginid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getConfig();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getInput();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getStatus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value7() {
		return getSuccess();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getInfo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value9() {
		return getOutput();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TestsRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TestsRecord value2(java.lang.String value) {
		setDescription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TestsRecord value3(java.lang.Integer value) {
		setPluginid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TestsRecord value4(java.lang.String value) {
		setConfig(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TestsRecord value5(java.lang.String value) {
		setInput(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TestsRecord value6(java.lang.String value) {
		setStatus(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TestsRecord value7(java.lang.Integer value) {
		setSuccess(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TestsRecord value8(java.lang.String value) {
		setInfo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TestsRecord value9(java.lang.String value) {
		setOutput(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TestsRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.Integer value3, java.lang.String value4, java.lang.String value5, java.lang.String value6, java.lang.Integer value7, java.lang.String value8, java.lang.String value9) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TestsRecord
	 */
	public TestsRecord() {
		super(sooth.entities.tables.Tests.TESTS);
	}

	/**
	 * Create a detached, initialised TestsRecord
	 */
	public TestsRecord(java.lang.Integer id, java.lang.String description, java.lang.Integer pluginid, java.lang.String config, java.lang.String input, java.lang.String status, java.lang.Integer success, java.lang.String info, java.lang.String output) {
		super(sooth.entities.tables.Tests.TESTS);

		setValue(0, id);
		setValue(1, description);
		setValue(2, pluginid);
		setValue(3, config);
		setValue(4, input);
		setValue(5, status);
		setValue(6, success);
		setValue(7, info);
		setValue(8, output);
	}
}
