/**
 * This class is generated by jOOQ
 */
package sooth.entities.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class XtestsRecord extends org.jooq.impl.UpdatableRecordImpl<sooth.entities.tables.records.XtestsRecord> implements org.jooq.Record6<java.lang.Integer, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String, java.lang.Integer> {

	private static final long serialVersionUID = -1160119781;

	/**
	 * Setter for <code>asmregen.xtests.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>asmregen.xtests.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>asmregen.xtests.description</code>.
	 */
	public void setDescription(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>asmregen.xtests.description</code>.
	 */
	public java.lang.String getDescription() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>asmregen.xtests.template</code>.
	 */
	public void setTemplate(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>asmregen.xtests.template</code>.
	 */
	public java.lang.String getTemplate() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>asmregen.xtests.count</code>.
	 */
	public void setCount(java.lang.Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>asmregen.xtests.count</code>.
	 */
	public java.lang.Integer getCount() {
		return (java.lang.Integer) getValue(3);
	}

	/**
	 * Setter for <code>asmregen.xtests.generated</code>.
	 */
	public void setGenerated(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>asmregen.xtests.generated</code>.
	 */
	public java.lang.String getGenerated() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>asmregen.xtests.lectureId</code>.
	 */
	public void setLectureid(java.lang.Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>asmregen.xtests.lectureId</code>.
	 */
	public java.lang.Integer getLectureid() {
		return (java.lang.Integer) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Integer, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Integer, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String, java.lang.Integer> valuesRow() {
		return (org.jooq.Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return sooth.entities.tables.Xtests.XTESTS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return sooth.entities.tables.Xtests.XTESTS.DESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return sooth.entities.tables.Xtests.XTESTS.TEMPLATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field4() {
		return sooth.entities.tables.Xtests.XTESTS.COUNT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return sooth.entities.tables.Xtests.XTESTS.GENERATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field6() {
		return sooth.entities.tables.Xtests.XTESTS.LECTUREID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getDescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getTemplate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value4() {
		return getCount();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getGenerated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value6() {
		return getLectureid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public XtestsRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public XtestsRecord value2(java.lang.String value) {
		setDescription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public XtestsRecord value3(java.lang.String value) {
		setTemplate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public XtestsRecord value4(java.lang.Integer value) {
		setCount(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public XtestsRecord value5(java.lang.String value) {
		setGenerated(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public XtestsRecord value6(java.lang.Integer value) {
		setLectureid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public XtestsRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3, java.lang.Integer value4, java.lang.String value5, java.lang.Integer value6) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached XtestsRecord
	 */
	public XtestsRecord() {
		super(sooth.entities.tables.Xtests.XTESTS);
	}

	/**
	 * Create a detached, initialised XtestsRecord
	 */
	public XtestsRecord(java.lang.Integer id, java.lang.String description, java.lang.String template, java.lang.Integer count, java.lang.String generated, java.lang.Integer lectureid) {
		super(sooth.entities.tables.Xtests.XTESTS);

		setValue(0, id);
		setValue(1, description);
		setValue(2, template);
		setValue(3, count);
		setValue(4, generated);
		setValue(5, lectureid);
	}
}
