/**
 * This class is generated by jOOQ
 */
package sooth.entities;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Asmregen extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = -707800190;

	/**
	 * The reference instance of <code>asmregen</code>
	 */
	public static final Asmregen ASMREGEN = new Asmregen();

	/**
	 * No further instances allowed
	 */
	private Asmregen() {
		super("asmregen");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			sooth.entities.tables.Assignments.ASSIGNMENTS,
			sooth.entities.tables.Attachments.ATTACHMENTS,
			sooth.entities.tables.Documents.DOCUMENTS,
			sooth.entities.tables.Groups.GROUPS,
			sooth.entities.tables.Lectures.LECTURES,
			sooth.entities.tables.Plugins.PLUGINS,
			sooth.entities.tables.Privileges.PRIVILEGES,
			sooth.entities.tables.Problems.PROBLEMS,
			sooth.entities.tables.Questions.QUESTIONS,
			sooth.entities.tables.Similarities.SIMILARITIES,
			sooth.entities.tables.Submissions.SUBMISSIONS,
			sooth.entities.tables.Subscriptions.SUBSCRIPTIONS,
			sooth.entities.tables.Tests.TESTS,
			sooth.entities.tables.Users.USERS,
			sooth.entities.tables.Xtests.XTESTS);
	}
}
