/**
 * This class is generated by jOOQ
 */
package sooth.entities;

/**
 * A class modelling foreign key relationships between tables of the <code>asmregen</code> 
 * schema
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.Identity<sooth.entities.tables.records.AssignmentsRecord, java.lang.Integer> IDENTITY_ASSIGNMENTS = Identities0.IDENTITY_ASSIGNMENTS;
	public static final org.jooq.Identity<sooth.entities.tables.records.AttachmentsRecord, java.lang.Integer> IDENTITY_ATTACHMENTS = Identities0.IDENTITY_ATTACHMENTS;
	public static final org.jooq.Identity<sooth.entities.tables.records.DocumentsRecord, java.lang.Integer> IDENTITY_DOCUMENTS = Identities0.IDENTITY_DOCUMENTS;
	public static final org.jooq.Identity<sooth.entities.tables.records.GroupsRecord, java.lang.Integer> IDENTITY_GROUPS = Identities0.IDENTITY_GROUPS;
	public static final org.jooq.Identity<sooth.entities.tables.records.LecturesRecord, java.lang.Integer> IDENTITY_LECTURES = Identities0.IDENTITY_LECTURES;
	public static final org.jooq.Identity<sooth.entities.tables.records.PluginsRecord, java.lang.Integer> IDENTITY_PLUGINS = Identities0.IDENTITY_PLUGINS;
	public static final org.jooq.Identity<sooth.entities.tables.records.PrivilegesRecord, java.lang.Integer> IDENTITY_PRIVILEGES = Identities0.IDENTITY_PRIVILEGES;
	public static final org.jooq.Identity<sooth.entities.tables.records.ProblemsRecord, java.lang.Integer> IDENTITY_PROBLEMS = Identities0.IDENTITY_PROBLEMS;
	public static final org.jooq.Identity<sooth.entities.tables.records.QuestionsRecord, java.lang.Integer> IDENTITY_QUESTIONS = Identities0.IDENTITY_QUESTIONS;
	public static final org.jooq.Identity<sooth.entities.tables.records.SimilaritiesRecord, java.lang.Integer> IDENTITY_SIMILARITIES = Identities0.IDENTITY_SIMILARITIES;
	public static final org.jooq.Identity<sooth.entities.tables.records.SubmissionsRecord, java.lang.Integer> IDENTITY_SUBMISSIONS = Identities0.IDENTITY_SUBMISSIONS;
	public static final org.jooq.Identity<sooth.entities.tables.records.SubscriptionsRecord, java.lang.Integer> IDENTITY_SUBSCRIPTIONS = Identities0.IDENTITY_SUBSCRIPTIONS;
	public static final org.jooq.Identity<sooth.entities.tables.records.TestsRecord, java.lang.Integer> IDENTITY_TESTS = Identities0.IDENTITY_TESTS;
	public static final org.jooq.Identity<sooth.entities.tables.records.UsersRecord, java.lang.Integer> IDENTITY_USERS = Identities0.IDENTITY_USERS;
	public static final org.jooq.Identity<sooth.entities.tables.records.XtestsRecord, java.lang.Integer> IDENTITY_XTESTS = Identities0.IDENTITY_XTESTS;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<sooth.entities.tables.records.AssignmentsRecord> KEY_ASSIGNMENTS_PRIMARY = UniqueKeys0.KEY_ASSIGNMENTS_PRIMARY;
	public static final org.jooq.UniqueKey<sooth.entities.tables.records.AttachmentsRecord> KEY_ATTACHMENTS_PRIMARY = UniqueKeys0.KEY_ATTACHMENTS_PRIMARY;
	public static final org.jooq.UniqueKey<sooth.entities.tables.records.DocumentsRecord> KEY_DOCUMENTS_PRIMARY = UniqueKeys0.KEY_DOCUMENTS_PRIMARY;
	public static final org.jooq.UniqueKey<sooth.entities.tables.records.GroupsRecord> KEY_GROUPS_PRIMARY = UniqueKeys0.KEY_GROUPS_PRIMARY;
	public static final org.jooq.UniqueKey<sooth.entities.tables.records.GroupsRecord> KEY_GROUPS_NAME = UniqueKeys0.KEY_GROUPS_NAME;
	public static final org.jooq.UniqueKey<sooth.entities.tables.records.LecturesRecord> KEY_LECTURES_PRIMARY = UniqueKeys0.KEY_LECTURES_PRIMARY;
	public static final org.jooq.UniqueKey<sooth.entities.tables.records.LecturesRecord> KEY_LECTURES_NAME = UniqueKeys0.KEY_LECTURES_NAME;
	public static final org.jooq.UniqueKey<sooth.entities.tables.records.PluginsRecord> KEY_PLUGINS_PRIMARY = UniqueKeys0.KEY_PLUGINS_PRIMARY;
	public static final org.jooq.UniqueKey<sooth.entities.tables.records.PluginsRecord> KEY_PLUGINS_NAME = UniqueKeys0.KEY_PLUGINS_NAME;
	public static final org.jooq.UniqueKey<sooth.entities.tables.records.PluginsRecord> KEY_PLUGINS_FOLDER = UniqueKeys0.KEY_PLUGINS_FOLDER;
	public static final org.jooq.UniqueKey<sooth.entities.tables.records.PrivilegesRecord> KEY_PRIVILEGES_PRIMARY = UniqueKeys0.KEY_PRIVILEGES_PRIMARY;
	public static final org.jooq.UniqueKey<sooth.entities.tables.records.PrivilegesRecord> KEY_PRIVILEGES_NAME = UniqueKeys0.KEY_PRIVILEGES_NAME;
	public static final org.jooq.UniqueKey<sooth.entities.tables.records.ProblemsRecord> KEY_PROBLEMS_PRIMARY = UniqueKeys0.KEY_PROBLEMS_PRIMARY;
	public static final org.jooq.UniqueKey<sooth.entities.tables.records.ProblemsRecord> KEY_PROBLEMS_NAME = UniqueKeys0.KEY_PROBLEMS_NAME;
	public static final org.jooq.UniqueKey<sooth.entities.tables.records.QuestionsRecord> KEY_QUESTIONS_PRIMARY = UniqueKeys0.KEY_QUESTIONS_PRIMARY;
	public static final org.jooq.UniqueKey<sooth.entities.tables.records.SimilaritiesRecord> KEY_SIMILARITIES_PRIMARY = UniqueKeys0.KEY_SIMILARITIES_PRIMARY;
	public static final org.jooq.UniqueKey<sooth.entities.tables.records.SubmissionsRecord> KEY_SUBMISSIONS_PRIMARY = UniqueKeys0.KEY_SUBMISSIONS_PRIMARY;
	public static final org.jooq.UniqueKey<sooth.entities.tables.records.SubscriptionsRecord> KEY_SUBSCRIPTIONS_PRIMARY = UniqueKeys0.KEY_SUBSCRIPTIONS_PRIMARY;
	public static final org.jooq.UniqueKey<sooth.entities.tables.records.TestsRecord> KEY_TESTS_PRIMARY = UniqueKeys0.KEY_TESTS_PRIMARY;
	public static final org.jooq.UniqueKey<sooth.entities.tables.records.UsersRecord> KEY_USERS_PRIMARY = UniqueKeys0.KEY_USERS_PRIMARY;
	public static final org.jooq.UniqueKey<sooth.entities.tables.records.UsersRecord> KEY_USERS_NAME = UniqueKeys0.KEY_USERS_NAME;
	public static final org.jooq.UniqueKey<sooth.entities.tables.records.XtestsRecord> KEY_XTESTS_PRIMARY = UniqueKeys0.KEY_XTESTS_PRIMARY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.ForeignKey<sooth.entities.tables.records.AssignmentsRecord, sooth.entities.tables.records.GroupsRecord> FK_308A50DDED8188B0 = ForeignKeys0.FK_308A50DDED8188B0;
	public static final org.jooq.ForeignKey<sooth.entities.tables.records.AssignmentsRecord, sooth.entities.tables.records.ProblemsRecord> FK_308A50DDBB4C47C8 = ForeignKeys0.FK_308A50DDBB4C47C8;
	public static final org.jooq.ForeignKey<sooth.entities.tables.records.AttachmentsRecord, sooth.entities.tables.records.LecturesRecord> FK_47C4FAD63BC48E00 = ForeignKeys0.FK_47C4FAD63BC48E00;
	public static final org.jooq.ForeignKey<sooth.entities.tables.records.DocumentsRecord, sooth.entities.tables.records.SubmissionsRecord> FK_A2B072889E929263 = ForeignKeys0.FK_A2B072889E929263;
	public static final org.jooq.ForeignKey<sooth.entities.tables.records.GroupsRecord, sooth.entities.tables.records.UsersRecord> FK_F06D3970E05EFD25 = ForeignKeys0.FK_F06D3970E05EFD25;
	public static final org.jooq.ForeignKey<sooth.entities.tables.records.GroupsRecord, sooth.entities.tables.records.LecturesRecord> FK_F06D39703BC48E00 = ForeignKeys0.FK_F06D39703BC48E00;
	public static final org.jooq.ForeignKey<sooth.entities.tables.records.LecturesRecord, sooth.entities.tables.records.UsersRecord> FK_63C861D0E05EFD25 = ForeignKeys0.FK_63C861D0E05EFD25;
	public static final org.jooq.ForeignKey<sooth.entities.tables.records.ProblemsRecord, sooth.entities.tables.records.PluginsRecord> FK_8E6662459A9A50E9 = ForeignKeys0.FK_8E6662459A9A50E9;
	public static final org.jooq.ForeignKey<sooth.entities.tables.records.ProblemsRecord, sooth.entities.tables.records.LecturesRecord> FK_8E6662453BC48E00 = ForeignKeys0.FK_8E6662453BC48E00;
	public static final org.jooq.ForeignKey<sooth.entities.tables.records.QuestionsRecord, sooth.entities.tables.records.LecturesRecord> FK_8ADC54D53BC48E00 = ForeignKeys0.FK_8ADC54D53BC48E00;
	public static final org.jooq.ForeignKey<sooth.entities.tables.records.SimilaritiesRecord, sooth.entities.tables.records.SubmissionsRecord> FK_DDD1B6BA5471A4A1 = ForeignKeys0.FK_DDD1B6BA5471A4A1;
	public static final org.jooq.ForeignKey<sooth.entities.tables.records.SimilaritiesRecord, sooth.entities.tables.records.SubmissionsRecord> FK_DDD1B6BA4A114A1D = ForeignKeys0.FK_DDD1B6BA4A114A1D;
	public static final org.jooq.ForeignKey<sooth.entities.tables.records.SubmissionsRecord, sooth.entities.tables.records.AssignmentsRecord> FK_3F6169F74526B08C = ForeignKeys0.FK_3F6169F74526B08C;
	public static final org.jooq.ForeignKey<sooth.entities.tables.records.SubmissionsRecord, sooth.entities.tables.records.UsersRecord> FK_3F6169F764B64DCC = ForeignKeys0.FK_3F6169F764B64DCC;
	public static final org.jooq.ForeignKey<sooth.entities.tables.records.SubscriptionsRecord, sooth.entities.tables.records.UsersRecord> FK_4778A0164B64DCC = ForeignKeys0.FK_4778A0164B64DCC;
	public static final org.jooq.ForeignKey<sooth.entities.tables.records.SubscriptionsRecord, sooth.entities.tables.records.GroupsRecord> FK_4778A01ED8188B0 = ForeignKeys0.FK_4778A01ED8188B0;
	public static final org.jooq.ForeignKey<sooth.entities.tables.records.TestsRecord, sooth.entities.tables.records.PluginsRecord> FK_1260FC5E9A9A50E9 = ForeignKeys0.FK_1260FC5E9A9A50E9;
	public static final org.jooq.ForeignKey<sooth.entities.tables.records.UsersRecord, sooth.entities.tables.records.PrivilegesRecord> FK_1483A5E98CDE5729 = ForeignKeys0.FK_1483A5E98CDE5729;
	public static final org.jooq.ForeignKey<sooth.entities.tables.records.XtestsRecord, sooth.entities.tables.records.LecturesRecord> FK_82F1254C3BC48E00 = ForeignKeys0.FK_82F1254C3BC48E00;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends org.jooq.impl.AbstractKeys {
		public static org.jooq.Identity<sooth.entities.tables.records.AssignmentsRecord, java.lang.Integer> IDENTITY_ASSIGNMENTS = createIdentity(sooth.entities.tables.Assignments.ASSIGNMENTS, sooth.entities.tables.Assignments.ASSIGNMENTS.ID);
		public static org.jooq.Identity<sooth.entities.tables.records.AttachmentsRecord, java.lang.Integer> IDENTITY_ATTACHMENTS = createIdentity(sooth.entities.tables.Attachments.ATTACHMENTS, sooth.entities.tables.Attachments.ATTACHMENTS.ID);
		public static org.jooq.Identity<sooth.entities.tables.records.DocumentsRecord, java.lang.Integer> IDENTITY_DOCUMENTS = createIdentity(sooth.entities.tables.Documents.DOCUMENTS, sooth.entities.tables.Documents.DOCUMENTS.ID);
		public static org.jooq.Identity<sooth.entities.tables.records.GroupsRecord, java.lang.Integer> IDENTITY_GROUPS = createIdentity(sooth.entities.tables.Groups.GROUPS, sooth.entities.tables.Groups.GROUPS.ID);
		public static org.jooq.Identity<sooth.entities.tables.records.LecturesRecord, java.lang.Integer> IDENTITY_LECTURES = createIdentity(sooth.entities.tables.Lectures.LECTURES, sooth.entities.tables.Lectures.LECTURES.ID);
		public static org.jooq.Identity<sooth.entities.tables.records.PluginsRecord, java.lang.Integer> IDENTITY_PLUGINS = createIdentity(sooth.entities.tables.Plugins.PLUGINS, sooth.entities.tables.Plugins.PLUGINS.ID);
		public static org.jooq.Identity<sooth.entities.tables.records.PrivilegesRecord, java.lang.Integer> IDENTITY_PRIVILEGES = createIdentity(sooth.entities.tables.Privileges.PRIVILEGES, sooth.entities.tables.Privileges.PRIVILEGES.ID);
		public static org.jooq.Identity<sooth.entities.tables.records.ProblemsRecord, java.lang.Integer> IDENTITY_PROBLEMS = createIdentity(sooth.entities.tables.Problems.PROBLEMS, sooth.entities.tables.Problems.PROBLEMS.ID);
		public static org.jooq.Identity<sooth.entities.tables.records.QuestionsRecord, java.lang.Integer> IDENTITY_QUESTIONS = createIdentity(sooth.entities.tables.Questions.QUESTIONS, sooth.entities.tables.Questions.QUESTIONS.ID);
		public static org.jooq.Identity<sooth.entities.tables.records.SimilaritiesRecord, java.lang.Integer> IDENTITY_SIMILARITIES = createIdentity(sooth.entities.tables.Similarities.SIMILARITIES, sooth.entities.tables.Similarities.SIMILARITIES.ID);
		public static org.jooq.Identity<sooth.entities.tables.records.SubmissionsRecord, java.lang.Integer> IDENTITY_SUBMISSIONS = createIdentity(sooth.entities.tables.Submissions.SUBMISSIONS, sooth.entities.tables.Submissions.SUBMISSIONS.ID);
		public static org.jooq.Identity<sooth.entities.tables.records.SubscriptionsRecord, java.lang.Integer> IDENTITY_SUBSCRIPTIONS = createIdentity(sooth.entities.tables.Subscriptions.SUBSCRIPTIONS, sooth.entities.tables.Subscriptions.SUBSCRIPTIONS.ID);
		public static org.jooq.Identity<sooth.entities.tables.records.TestsRecord, java.lang.Integer> IDENTITY_TESTS = createIdentity(sooth.entities.tables.Tests.TESTS, sooth.entities.tables.Tests.TESTS.ID);
		public static org.jooq.Identity<sooth.entities.tables.records.UsersRecord, java.lang.Integer> IDENTITY_USERS = createIdentity(sooth.entities.tables.Users.USERS, sooth.entities.tables.Users.USERS.ID);
		public static org.jooq.Identity<sooth.entities.tables.records.XtestsRecord, java.lang.Integer> IDENTITY_XTESTS = createIdentity(sooth.entities.tables.Xtests.XTESTS, sooth.entities.tables.Xtests.XTESTS.ID);
	}

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<sooth.entities.tables.records.AssignmentsRecord> KEY_ASSIGNMENTS_PRIMARY = createUniqueKey(sooth.entities.tables.Assignments.ASSIGNMENTS, sooth.entities.tables.Assignments.ASSIGNMENTS.ID);
		public static final org.jooq.UniqueKey<sooth.entities.tables.records.AttachmentsRecord> KEY_ATTACHMENTS_PRIMARY = createUniqueKey(sooth.entities.tables.Attachments.ATTACHMENTS, sooth.entities.tables.Attachments.ATTACHMENTS.ID);
		public static final org.jooq.UniqueKey<sooth.entities.tables.records.DocumentsRecord> KEY_DOCUMENTS_PRIMARY = createUniqueKey(sooth.entities.tables.Documents.DOCUMENTS, sooth.entities.tables.Documents.DOCUMENTS.ID);
		public static final org.jooq.UniqueKey<sooth.entities.tables.records.GroupsRecord> KEY_GROUPS_PRIMARY = createUniqueKey(sooth.entities.tables.Groups.GROUPS, sooth.entities.tables.Groups.GROUPS.ID);
		public static final org.jooq.UniqueKey<sooth.entities.tables.records.GroupsRecord> KEY_GROUPS_NAME = createUniqueKey(sooth.entities.tables.Groups.GROUPS, sooth.entities.tables.Groups.GROUPS.NAME);
		public static final org.jooq.UniqueKey<sooth.entities.tables.records.LecturesRecord> KEY_LECTURES_PRIMARY = createUniqueKey(sooth.entities.tables.Lectures.LECTURES, sooth.entities.tables.Lectures.LECTURES.ID);
		public static final org.jooq.UniqueKey<sooth.entities.tables.records.LecturesRecord> KEY_LECTURES_NAME = createUniqueKey(sooth.entities.tables.Lectures.LECTURES, sooth.entities.tables.Lectures.LECTURES.NAME);
		public static final org.jooq.UniqueKey<sooth.entities.tables.records.PluginsRecord> KEY_PLUGINS_PRIMARY = createUniqueKey(sooth.entities.tables.Plugins.PLUGINS, sooth.entities.tables.Plugins.PLUGINS.ID);
		public static final org.jooq.UniqueKey<sooth.entities.tables.records.PluginsRecord> KEY_PLUGINS_NAME = createUniqueKey(sooth.entities.tables.Plugins.PLUGINS, sooth.entities.tables.Plugins.PLUGINS.NAME);
		public static final org.jooq.UniqueKey<sooth.entities.tables.records.PluginsRecord> KEY_PLUGINS_FOLDER = createUniqueKey(sooth.entities.tables.Plugins.PLUGINS, sooth.entities.tables.Plugins.PLUGINS.MAINFILE);
		public static final org.jooq.UniqueKey<sooth.entities.tables.records.PrivilegesRecord> KEY_PRIVILEGES_PRIMARY = createUniqueKey(sooth.entities.tables.Privileges.PRIVILEGES, sooth.entities.tables.Privileges.PRIVILEGES.ID);
		public static final org.jooq.UniqueKey<sooth.entities.tables.records.PrivilegesRecord> KEY_PRIVILEGES_NAME = createUniqueKey(sooth.entities.tables.Privileges.PRIVILEGES, sooth.entities.tables.Privileges.PRIVILEGES.NAME);
		public static final org.jooq.UniqueKey<sooth.entities.tables.records.ProblemsRecord> KEY_PROBLEMS_PRIMARY = createUniqueKey(sooth.entities.tables.Problems.PROBLEMS, sooth.entities.tables.Problems.PROBLEMS.ID);
		public static final org.jooq.UniqueKey<sooth.entities.tables.records.ProblemsRecord> KEY_PROBLEMS_NAME = createUniqueKey(sooth.entities.tables.Problems.PROBLEMS, sooth.entities.tables.Problems.PROBLEMS.NAME);
		public static final org.jooq.UniqueKey<sooth.entities.tables.records.QuestionsRecord> KEY_QUESTIONS_PRIMARY = createUniqueKey(sooth.entities.tables.Questions.QUESTIONS, sooth.entities.tables.Questions.QUESTIONS.ID);
		public static final org.jooq.UniqueKey<sooth.entities.tables.records.SimilaritiesRecord> KEY_SIMILARITIES_PRIMARY = createUniqueKey(sooth.entities.tables.Similarities.SIMILARITIES, sooth.entities.tables.Similarities.SIMILARITIES.ID);
		public static final org.jooq.UniqueKey<sooth.entities.tables.records.SubmissionsRecord> KEY_SUBMISSIONS_PRIMARY = createUniqueKey(sooth.entities.tables.Submissions.SUBMISSIONS, sooth.entities.tables.Submissions.SUBMISSIONS.ID);
		public static final org.jooq.UniqueKey<sooth.entities.tables.records.SubscriptionsRecord> KEY_SUBSCRIPTIONS_PRIMARY = createUniqueKey(sooth.entities.tables.Subscriptions.SUBSCRIPTIONS, sooth.entities.tables.Subscriptions.SUBSCRIPTIONS.ID);
		public static final org.jooq.UniqueKey<sooth.entities.tables.records.TestsRecord> KEY_TESTS_PRIMARY = createUniqueKey(sooth.entities.tables.Tests.TESTS, sooth.entities.tables.Tests.TESTS.ID);
		public static final org.jooq.UniqueKey<sooth.entities.tables.records.UsersRecord> KEY_USERS_PRIMARY = createUniqueKey(sooth.entities.tables.Users.USERS, sooth.entities.tables.Users.USERS.ID);
		public static final org.jooq.UniqueKey<sooth.entities.tables.records.UsersRecord> KEY_USERS_NAME = createUniqueKey(sooth.entities.tables.Users.USERS, sooth.entities.tables.Users.USERS.NAME);
		public static final org.jooq.UniqueKey<sooth.entities.tables.records.XtestsRecord> KEY_XTESTS_PRIMARY = createUniqueKey(sooth.entities.tables.Xtests.XTESTS, sooth.entities.tables.Xtests.XTESTS.ID);
	}

	private static class ForeignKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.ForeignKey<sooth.entities.tables.records.AssignmentsRecord, sooth.entities.tables.records.GroupsRecord> FK_308A50DDED8188B0 = createForeignKey(sooth.entities.Keys.KEY_GROUPS_PRIMARY, sooth.entities.tables.Assignments.ASSIGNMENTS, sooth.entities.tables.Assignments.ASSIGNMENTS.GROUPID);
		public static final org.jooq.ForeignKey<sooth.entities.tables.records.AssignmentsRecord, sooth.entities.tables.records.ProblemsRecord> FK_308A50DDBB4C47C8 = createForeignKey(sooth.entities.Keys.KEY_PROBLEMS_PRIMARY, sooth.entities.tables.Assignments.ASSIGNMENTS, sooth.entities.tables.Assignments.ASSIGNMENTS.PROBLEMID);
		public static final org.jooq.ForeignKey<sooth.entities.tables.records.AttachmentsRecord, sooth.entities.tables.records.LecturesRecord> FK_47C4FAD63BC48E00 = createForeignKey(sooth.entities.Keys.KEY_LECTURES_PRIMARY, sooth.entities.tables.Attachments.ATTACHMENTS, sooth.entities.tables.Attachments.ATTACHMENTS.LECTUREID);
		public static final org.jooq.ForeignKey<sooth.entities.tables.records.DocumentsRecord, sooth.entities.tables.records.SubmissionsRecord> FK_A2B072889E929263 = createForeignKey(sooth.entities.Keys.KEY_SUBMISSIONS_PRIMARY, sooth.entities.tables.Documents.DOCUMENTS, sooth.entities.tables.Documents.DOCUMENTS.SUBMISSIONID);
		public static final org.jooq.ForeignKey<sooth.entities.tables.records.GroupsRecord, sooth.entities.tables.records.UsersRecord> FK_F06D3970E05EFD25 = createForeignKey(sooth.entities.Keys.KEY_USERS_PRIMARY, sooth.entities.tables.Groups.GROUPS, sooth.entities.tables.Groups.GROUPS.OWNERID);
		public static final org.jooq.ForeignKey<sooth.entities.tables.records.GroupsRecord, sooth.entities.tables.records.LecturesRecord> FK_F06D39703BC48E00 = createForeignKey(sooth.entities.Keys.KEY_LECTURES_PRIMARY, sooth.entities.tables.Groups.GROUPS, sooth.entities.tables.Groups.GROUPS.LECTUREID);
		public static final org.jooq.ForeignKey<sooth.entities.tables.records.LecturesRecord, sooth.entities.tables.records.UsersRecord> FK_63C861D0E05EFD25 = createForeignKey(sooth.entities.Keys.KEY_USERS_PRIMARY, sooth.entities.tables.Lectures.LECTURES, sooth.entities.tables.Lectures.LECTURES.OWNERID);
		public static final org.jooq.ForeignKey<sooth.entities.tables.records.ProblemsRecord, sooth.entities.tables.records.PluginsRecord> FK_8E6662459A9A50E9 = createForeignKey(sooth.entities.Keys.KEY_PLUGINS_PRIMARY, sooth.entities.tables.Problems.PROBLEMS, sooth.entities.tables.Problems.PROBLEMS.PLUGINID);
		public static final org.jooq.ForeignKey<sooth.entities.tables.records.ProblemsRecord, sooth.entities.tables.records.LecturesRecord> FK_8E6662453BC48E00 = createForeignKey(sooth.entities.Keys.KEY_LECTURES_PRIMARY, sooth.entities.tables.Problems.PROBLEMS, sooth.entities.tables.Problems.PROBLEMS.LECTUREID);
		public static final org.jooq.ForeignKey<sooth.entities.tables.records.QuestionsRecord, sooth.entities.tables.records.LecturesRecord> FK_8ADC54D53BC48E00 = createForeignKey(sooth.entities.Keys.KEY_LECTURES_PRIMARY, sooth.entities.tables.Questions.QUESTIONS, sooth.entities.tables.Questions.QUESTIONS.LECTUREID);
		public static final org.jooq.ForeignKey<sooth.entities.tables.records.SimilaritiesRecord, sooth.entities.tables.records.SubmissionsRecord> FK_DDD1B6BA5471A4A1 = createForeignKey(sooth.entities.Keys.KEY_SUBMISSIONS_PRIMARY, sooth.entities.tables.Similarities.SIMILARITIES, sooth.entities.tables.Similarities.SIMILARITIES.OLDSUBMISSIONID);
		public static final org.jooq.ForeignKey<sooth.entities.tables.records.SimilaritiesRecord, sooth.entities.tables.records.SubmissionsRecord> FK_DDD1B6BA4A114A1D = createForeignKey(sooth.entities.Keys.KEY_SUBMISSIONS_PRIMARY, sooth.entities.tables.Similarities.SIMILARITIES, sooth.entities.tables.Similarities.SIMILARITIES.NEWSUBMISSIONID);
		public static final org.jooq.ForeignKey<sooth.entities.tables.records.SubmissionsRecord, sooth.entities.tables.records.AssignmentsRecord> FK_3F6169F74526B08C = createForeignKey(sooth.entities.Keys.KEY_ASSIGNMENTS_PRIMARY, sooth.entities.tables.Submissions.SUBMISSIONS, sooth.entities.tables.Submissions.SUBMISSIONS.ASSIGNMENTID);
		public static final org.jooq.ForeignKey<sooth.entities.tables.records.SubmissionsRecord, sooth.entities.tables.records.UsersRecord> FK_3F6169F764B64DCC = createForeignKey(sooth.entities.Keys.KEY_USERS_PRIMARY, sooth.entities.tables.Submissions.SUBMISSIONS, sooth.entities.tables.Submissions.SUBMISSIONS.USERID);
		public static final org.jooq.ForeignKey<sooth.entities.tables.records.SubscriptionsRecord, sooth.entities.tables.records.UsersRecord> FK_4778A0164B64DCC = createForeignKey(sooth.entities.Keys.KEY_USERS_PRIMARY, sooth.entities.tables.Subscriptions.SUBSCRIPTIONS, sooth.entities.tables.Subscriptions.SUBSCRIPTIONS.USERID);
		public static final org.jooq.ForeignKey<sooth.entities.tables.records.SubscriptionsRecord, sooth.entities.tables.records.GroupsRecord> FK_4778A01ED8188B0 = createForeignKey(sooth.entities.Keys.KEY_GROUPS_PRIMARY, sooth.entities.tables.Subscriptions.SUBSCRIPTIONS, sooth.entities.tables.Subscriptions.SUBSCRIPTIONS.GROUPID);
		public static final org.jooq.ForeignKey<sooth.entities.tables.records.TestsRecord, sooth.entities.tables.records.PluginsRecord> FK_1260FC5E9A9A50E9 = createForeignKey(sooth.entities.Keys.KEY_PLUGINS_PRIMARY, sooth.entities.tables.Tests.TESTS, sooth.entities.tables.Tests.TESTS.PLUGINID);
		public static final org.jooq.ForeignKey<sooth.entities.tables.records.UsersRecord, sooth.entities.tables.records.PrivilegesRecord> FK_1483A5E98CDE5729 = createForeignKey(sooth.entities.Keys.KEY_PRIVILEGES_PRIMARY, sooth.entities.tables.Users.USERS, sooth.entities.tables.Users.USERS.TYPE);
		public static final org.jooq.ForeignKey<sooth.entities.tables.records.XtestsRecord, sooth.entities.tables.records.LecturesRecord> FK_82F1254C3BC48E00 = createForeignKey(sooth.entities.Keys.KEY_LECTURES_PRIMARY, sooth.entities.tables.Xtests.XTESTS, sooth.entities.tables.Xtests.XTESTS.LECTUREID);
	}
}
