/**
 * This class is generated by jOOQ
 */
package sooth.entities;

/**
 * Convenience access to all tables in asmregen
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table asmregen.assignments
	 */
	public static final sooth.entities.tables.Assignments ASSIGNMENTS = sooth.entities.tables.Assignments.ASSIGNMENTS;

	/**
	 * The table asmregen.attachments
	 */
	public static final sooth.entities.tables.Attachments ATTACHMENTS = sooth.entities.tables.Attachments.ATTACHMENTS;

	/**
	 * The table asmregen.documents
	 */
	public static final sooth.entities.tables.Documents DOCUMENTS = sooth.entities.tables.Documents.DOCUMENTS;

	/**
	 * The table asmregen.groups
	 */
	public static final sooth.entities.tables.Groups GROUPS = sooth.entities.tables.Groups.GROUPS;

	/**
	 * The table asmregen.lectures
	 */
	public static final sooth.entities.tables.Lectures LECTURES = sooth.entities.tables.Lectures.LECTURES;

	/**
	 * The table asmregen.plugins
	 */
	public static final sooth.entities.tables.Plugins PLUGINS = sooth.entities.tables.Plugins.PLUGINS;

	/**
	 * The table asmregen.privileges
	 */
	public static final sooth.entities.tables.Privileges PRIVILEGES = sooth.entities.tables.Privileges.PRIVILEGES;

	/**
	 * The table asmregen.problems
	 */
	public static final sooth.entities.tables.Problems PROBLEMS = sooth.entities.tables.Problems.PROBLEMS;

	/**
	 * The table asmregen.questions
	 */
	public static final sooth.entities.tables.Questions QUESTIONS = sooth.entities.tables.Questions.QUESTIONS;

	/**
	 * The table asmregen.similarities
	 */
	public static final sooth.entities.tables.Similarities SIMILARITIES = sooth.entities.tables.Similarities.SIMILARITIES;

	/**
	 * The table asmregen.submissions
	 */
	public static final sooth.entities.tables.Submissions SUBMISSIONS = sooth.entities.tables.Submissions.SUBMISSIONS;

	/**
	 * The table asmregen.subscriptions
	 */
	public static final sooth.entities.tables.Subscriptions SUBSCRIPTIONS = sooth.entities.tables.Subscriptions.SUBSCRIPTIONS;

	/**
	 * The table asmregen.tests
	 */
	public static final sooth.entities.tables.Tests TESTS = sooth.entities.tables.Tests.TESTS;

	/**
	 * The table asmregen.users
	 */
	public static final sooth.entities.tables.Users USERS = sooth.entities.tables.Users.USERS;

	/**
	 * The table asmregen.xtests
	 */
	public static final sooth.entities.tables.Xtests XTESTS = sooth.entities.tables.Xtests.XTESTS;
}
